
IF OBJECT_ID('UDF_IntegerOnlySummed') IS NOT NULL 
BEGIN
	DROP FUNCTION UDF_IntegerOnlySummed
END
go
CREATE FUNCTION UDF_IntegerOnlySummed
(
	@STRING NVARCHAR(4000)
)
--Returns the sum of all integers found in a given string
RETURNS INT
BEGIN
    WHILE PATINDEX('%[^0-9]%',@STRING) > 0
        SET @STRING = STUFF(@STRING,PATINDEX('%[^0-9]%',@STRING),1,'')
	
	DECLARE @SUM INT=0
	DECLARE @INCREMENT INT=1

	WHILE @INCREMENT<=LEN(@STRING)
	BEGIN

		SET @SUM=@SUM+CAST(SUBSTRING(@STRING,@INCREMENT,1) AS INT)

	SET @INCREMENT=@INCREMENT+1
	END

    RETURN @SUM
END
GO
