IF OBJECT_ID('UDF_String2Money') IS NOT NULL 
BEGIN
	DROP FUNCTION UDF_String2Money
END
GO
CREATE FUNCTION UDF_String2Money(@STRING NVARCHAR(4000)) 
RETURNS MONEY
BEGIN 
	IF REPLACE(@STRING,' ','')=''
	BEGIN
		RETURN NULL
	END

	RETURN ISNULL(TRY_CAST(@STRING AS MONEY),[dbo].[UDF_String2Float](@STRING))

END 
