IF OBJECT_ID('UDF_String2Float') IS NOT NULL 
BEGIN
	DROP FUNCTION UDF_String2Float
END
GO
CREATE FUNCTION UDF_String2Float(@STRING NVARCHAR(4000)) 
RETURNS FLOAT
BEGIN 
	IF RIGHT(RTRIM(@STRING),1) = '%'
	BEGIN 
		RETURN TRY_CONVERT(FLOAT,dbo.UDF_String2Numeric(@STRING))/100
	END 

	RETURN TRY_CONVERT(FLOAT,dbo.UDF_String2Numeric(@STRING))
END 
