IF OBJECT_ID('UDF_String2Numeric') IS NOT NULL 
BEGIN
	DROP FUNCTION UDF_String2Numeric
END
GO
CREATE FUNCTION UDF_String2Numeric(@STRING NVARCHAR(4000)) 
RETURNS NVARCHAR(4000)
BEGIN 
	DECLARE @NUMERIC AS NVARCHAR(4000)

	IF @STRING = ''
	BEGIN 
		RETURN NULL 
	END 
	ELSE IF dbo.UDF_NumbersOnly_Alternative(@STRING) = ''
	BEGIN 
		RETURN NULL 
	END 
	ELSE IF PATINDEX('%[a-df-z]%',@STRING) > 0
	BEGIN 
		RETURN NULL 
	END 

	IF LEFT(LTRIM(@STRING),1) = '(' AND RIGHT(RTRIM(@STRING),1) = ')'
	BEGIN 
		SET @NUMERIC = '-'+dbo.UDF_NumbersOnly_Alternative(@STRING)
		RETURN @NUMERIC
	END 

	SET @NUMERIC = dbo.UDF_NumbersOnly_Alternative(@STRING)

	RETURN @NUMERIC
END 
